name: 'ZenHub link PR to issue with Branch Prefixes'
description: 'Create ZenHub link between pull request and issue based on the branch prefix'
author: 'CoBloX Team'
branding:
  icon: git-pull-request
  color: purple
inputs:
  ZENHUB_TOKEN:
    description: 'A ZenHub API token'
    required: true
  BRANCH_PREFIX:
    description: 'A prefix for your branch names'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
